FUNCTION L_TO_CONFIRM
  IMPORTING
    VALUE(I_LGNUM) LIKE LTAK-LGNUM
    VALUE(I_TANUM) LIKE LTAK-TANUM
    VALUE(I_SQUIT) LIKE RL03T-SQUIT DEFAULT SPACE
    VALUE(I_QUKNZ) LIKE RL03T-QUKNZ DEFAULT SPACE
    VALUE(I_SUBST) LIKE RL03T-SUBST DEFAULT SPACE
    VALUE(I_QNAME) LIKE LTAP-QNAME DEFAULT SY-UNAME
    VALUE(I_ENAME) LIKE LTAP-ENAME DEFAULT SY-UNAME
    VALUE(I_SOLEX) LIKE LTAK-SOLEX DEFAULT 0
    VALUE(I_PERNR) LIKE LTAK-PERNR DEFAULT 0
    VALUE(I_STDAT) LIKE LTAK-STDAT DEFAULT INIT_DATUM
    VALUE(I_STUZT) LIKE LTAK-STUZT DEFAULT 0
    VALUE(I_ENDAT) LIKE LTAK-ENDAT DEFAULT INIT_DATUM
    VALUE(I_ENUZT) LIKE LTAK-ENUZT DEFAULT 0
    VALUE(I_ISTWM) LIKE LTAK-ISTWM DEFAULT 0
    VALUE(I_KOMIM) LIKE RL03T-KOMIM DEFAULT SPACE
    VALUE(I_EINLM) LIKE RL03T-EINLM DEFAULT SPACE
    VALUE(I_TBELI) LIKE RL03T-TBELI DEFAULT SPACE
    VALUE(I_UPDATE_TASK) LIKE RL03A-VERBU DEFAULT SPACE
    VALUE(I_COMMIT_WORK) LIKE RL03B-COMIT DEFAULT 'X'
    VALUE(I_AUSFB) LIKE LTAK-AUSFB DEFAULT SPACE
  TABLES
    T_LTAP_CONF LIKE LTAP_CONF
    T_LTAP_CONF_HU LIKE LTAP_CONF_HU OPTIONAL
    T_LTAP_CONF_HU_SERIAL LIKE LTAP_CONF_HU_SERIAL OPTIONAL
  EXCEPTIONS
    TO_CONFIRMED
    TO_DOESNT_EXIST
    ITEM_CONFIRMED
    ITEM_SUBSYSTEM
    ITEM_DOESNT_EXIST
    ITEM_WITHOUT_ZERO_STOCK_CHECK
    ITEM_WITH_ZERO_STOCK_CHECK
    ONE_ITEM_WITH_ZERO_STOCK_CHECK
    ITEM_SU_BULK_STORAGE
    ITEM_NO_SU_BULK_STORAGE
    ONE_ITEM_SU_BULK_STORAGE
    FOREIGN_LOCK
    SQUIT_OR_QUANTITIES
    VQUIT_OR_QUANTITIES
    BQUIT_OR_QUANTITIES
    QUANTITY_WRONG
    DOUBLE_LINES
    KZDIF_WRONG
    NO_DIFFERENCE
    NO_NEGATIVE_QUANTITIES
    WRONG_ZERO_STOCK_CHECK
    SU_NOT_FOUND
    NO_STOCK_ON_SU
    SU_WRONG
    TOO_MANY_SU
    NOTHING_TO_DO
    NO_UNIT_OF_MEASURE
    XFELD_WRONG
    UPDATE_WITHOUT_COMMIT
    NO_AUTHORITY
    LQNUM_MISSING
    CHARG_MISSING
    NO_SOBKZ
    NO_CHARG
    NLPLA_WRONG
    TWO_STEP_CONFIRMATION_REQUIRED
    TWO_STEP_CONF_NOT_ALLOWED
    PICK_CONFIRMATION_MISSING
    QUKNZ_WRONG
    HU_DATA_WRONG
    NO_HU_DATA_REQUIRED
    HU_DATA_MISSING
    HU_NOT_FOUND
    PICKING_OF_HU_NOT_POSSIBLE
    NOT_ENOUGH_STOCK_IN_HU
    SERIAL_NUMBER_DATA_WRONG
    SERIAL_NUMBERS_NOT_REQUIRED
    NO_DIFFERENCES_ALLOWED
    SERIAL_NUMBER_NOT_AVAILABLE
    SERIAL_NUMBER_DATA_MISSING
    TO_ITEM_SPLIT_NOT_ALLOWED
    INPUT_WRONG.




 DATA: LV_LTAP_CONF_LINES LIKE SY-TABIX,                  "n_652425
       LV_TAP_TABIX       LIKE SY-TABIX.


*........Initialisierung................................................

* Initialization for serial numbers                      "n_1842569
  PERFORM SERIAL_INTTAB_REFRESH .                        "n_1842569

  CALL FUNCTION 'L_SAPLL03A_INIT_INT'.
  PERFORM SAPML03T_INIT(SAPML03T).
  CALL FUNCTION 'HU_PACKING_REFRESH'.
  CALL FUNCTION 'LE_DELIVERY_REFRESH_BUFFER'
    EXCEPTIONS
      NO_KEY_SPECIFIED       = 0
      OTHERS                 = 0.
  FLG_KEINE_DYNPROS = CON_TRUE.
  GF_FLG_HU_DATA_CHECKED = CON_FALSE.
  RL03T-QUKNZ = I_QUKNZ.

*........Steuertabellen lesen...........................................

  PERFORM T340_LESEN(SAPML03T) USING CON_TCODE_QUITTIEREN.
  PERFORM T300_LESEN(SAPML03T) USING I_LGNUM.
  PERFORM T340D_LESEN(SAPML03T) USING I_LGNUM.
  PERFORM BERECHTIGUNG_LGNUM(SAPFL000) USING CON_BER_MP I_LGNUM.

*........Transportauftrag lesen und sperren.............................

  if i_squit is initial and
     not t340d-later is initial.
    loop at t_ltap_conf.
      move-corresponding t_ltap_conf to gt_ltap_enqueue.
      collect gt_ltap_enqueue.
    endloop.
  endif.

* If only one TO-item is confirmed (like LT11), than       "v_n_652425
* fill INIT_TAPOS
  CLEAR INIT_TAPOS.                                          "n_654783
  IF I_SQUIT IS INITIAL.
    DESCRIBE TABLE T_LTAP_CONF LINES LV_LTAP_CONF_LINES.
    IF LV_LTAP_CONF_LINES = 1.
      READ TABLE T_LTAP_CONF INDEX 1.
      INIT_TAPOS = T_LTAP_CONF-TAPOS.
    ENDIF.
  ENDIF.                                                   "^_n_652425

  PERFORM TA_LESEN(SAPML03T) USING I_LGNUM I_TANUM INIT_TAPOS.

* Filter TO items, that are not requested                  "v_n_652425
  IF I_SQUIT IS INITIAL     AND
     LV_LTAP_CONF_LINES GT 1.
    LOOP AT TAP.
      CLEAR LV_TAP_TABIX.
      LV_TAP_TABIX = SY-TABIX.
      READ TABLE T_LTAP_CONF WITH KEY TANUM = TAP-TANUM
                                      TAPOS = TAP-TAPOS
      TRANSPORTING NO FIELDS.
      IF NOT SY-SUBRC IS INITIAL.
        DELETE TAP INDEX LV_TAP_TABIX.
      ENDIF.
    ENDLOOP.
    CLEAR TAP.
  ENDIF.                                                   "^_n_652425

* this correction removed by SAP note 3042429
**v_n_2761615   Update name of counter in case of Zero stock check
*  DATA LS_TAP TYPE LTAP_VB.
*  LOOP AT TAP INTO LS_TAP WHERE KZNKO = 'X'.
*    LS_TAP-QNAME = I_QNAME.
*    MODIFY TAP FROM LS_TAP.
*  ENDLOOP.
**^_n_2761615

  PERFORM T333_LESEN(SAPML03T) USING LTAK-LGNUM LTAK-BWLVS.
  PERFORM KZ_WM_MENGE_ERMITTELN(SAPML03T) USING I_KOMIM I_EINLM
                                                T333-WMMUE.

*........Prüfungen der Übergabeparameter................................

  FLG_CHARGENSPLIT = CON_FALSE.
  PERFORM QUITTIERUNG_PRUEFEN_ISTDATEN USING FLG_ISTDATEN.
  IF LTAK-MINWM = CON_X.
    PERFORM QUITTIERUNG_PRUEFEN_MINIWM.
  ENDIF.
  PERFORM QUITTIERUNG_PRUEFEN.

*........Quittieren über Funktionsbausteine.............................

  PERFORM QUITTIEREN.

*........Aufruf Verbuchung..............................................

  RL03A-KOMIM = I_KOMIM.
  RL03A-EINLM = I_EINLM.
  RL03A-TBELI = I_TBELI.
  RL03A-VERBU = I_UPDATE_TASK.
  rl03a-quknz = i_quknz.
  CALL FUNCTION 'L_TO_CONFIRM_INT'
       EXPORTING
            I_RL03A = RL03A.

  PERFORM COMMIT_WORK.

ENDFUNCTION.